apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - namespace: engineering-dev
      - namespace: engineering-prod
  template:
    metadata:
      name: '{{namespace}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/applicationset.git
        targetRevision: HEAD
        path: examples/list-generator/guestbook/{{namespace}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
